apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator-github-webhook.serviceAccountName" . }}
  labels:
    {{- include "operator-github-webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
