# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/master/c2cciutils/schema.json

checks:
  required_workflows:
    codeql.yaml: False
  codespell:
    ignore_re:
      - docker/poetry\.lock

publish:
  docker:
    images:
      - name: camptocamp/github-webhook-operator
