#!/bin/bash -eu

kubectl config set-context --current --namespace=default

echo === events ===
kubectl get events

echo === pods ===
kubectl get pods --output=wide

for name in $(kubectl get pods --output=name)
do
  echo =====================
  echo $name
  echo === describe ===
  kubectl describe $name
  echo === logs ===
  kubectl logs $name
done
